packages:
  - "packages/*"

catalog:
  # Shared dependencies across workspace
  typescript: ^5.4.5
  "@types/node": ^20.12.7
  vitest: ^1.6.0
  eslint: ^8.57.0

# pnpm configuration
prefer-workspace-packages: true
link-workspace-packages: deep
shared-workspace-lockfile: true
save-workspace-protocol: rolling
