packages:
  - packages/*

link-workspace-packages: deep

onlyBuiltDependencies:
  - canvas
  - esbuild
  - pkcs11js
  - unrs-resolver

prefer-workspace-packages: true

save-workspace-protocol: rolling

shared-workspace-lockfile: true

strictPeerDependencies: false
